# -*- coding: utf-8 -*-
"""Aaditya_Amlan_Panda_220007_Lab_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoMojj7XWBAnNb6KTXeZ1MUYh5zqqmEt
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

data = pd.read_csv('/content/Copy of dataset_lab12.csv').values
X = data[:,0]
Y = data[:,1]

X = X.reshape(-1,1)
Y = Y.reshape(-1,1)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model = Sequential([
    Dense(5,activation='relu',input_shape=(1,)),
    Dense(4,activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam',loss='mse')

history = model.fit(X_train,Y_train,epochs=3000,validation_data=(X_test,Y_test))

Y_pred = model.predict(X)

plt.scatter(X,Y,label = "Actual Data")
plt.plot(X,Y_pred,color='red',label = "Predicted Data")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()
plt.title("Actual and Predicted data")
plt.show()

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Test Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.title("Loss curve")
plt.show()